service: ${self:custom.project}-compare

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"
  - serverless-bundle
  - "@stratiformdigital/serverless-idempotency-helper"
  - "@stratiformdigital/serverless-online"
  - "@stratiformdigital/serverless-iam-helper"
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: ${ssm:/configuration/${sls:stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${ssm:/configuration/${sls:stage}/iam/permissionsBoundaryPolicyArn, ssm:/configuration/default/iam/permissionsBoundaryPolicyArn, ""}
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            - ${param:mmdlTableArn}
            - ${param:seatoolTableArn}
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - !Ref MMDLAlertingStateMachine
            - !Sub "arn:aws:states:${self:provider.region}:${AWS::AccountId}:execution:${MMDLAlertingStateMachine.Name}:*"
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource:
            - !Sub "arn:aws:ses:${self:provider.region}:${AWS::AccountId}:identity/*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - !Sub "arn:aws:secretsmanager:${self:provider.region}:${AWS::AccountId}:secret:${self:custom.project}/${sls:stage}/alerts*"
        - Effect: Allow
          Action:
            - secretsmanager:ListSecrets
          Resource: "*"

params:
  master:
    initialWaitSec: 172800
    signedSinceChoiceDays: 4
    recordAgeChoiceDays: 251
  val:
    initialWaitSec: 172800
    signedSinceChoiceDays: 4
    recordAgeChoiceDays: 251
  production:
    initialWaitSec: 172800
    signedSinceChoiceDays: 4
    recordAgeChoiceDays: 251
  default:
    initialWaitSec: 2
    signedSinceChoiceDays: 0
    recordAgeChoiceDays: 0

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production
  secretId: ${self:custom.project}/${sls:stage}/alerts

functions:
  workflowStarter:
    handler: handlers/workflowStarter.handler
    events:
      - stream:
          arn: ${param:mmdlTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 0
    environment:
      stateMachineArn: !Ref MMDLAlertingStateMachine
      region: ${self:provider.region}
    maximumRetryAttempts: 0
  compare:
    handler: handlers/compare.handler
    environment:
      region: ${self:provider.region}
      mmdlTableName: ${param:mmdlTableName}
      seatoolTableName: ${param:seatoolTableName}
  seatoolRecordExist:
    handler: handlers/seatoolRecordExist.handler
    environment:
      region: ${self:provider.region}
      seatoolTableName: ${param:seatoolTableName}
  sendAlert:
    handler: handlers/sendAlert.handler
    environment:
      region: ${self:provider.region}
      project: ${self:custom.project}
      stage: ${sls:stage}
  daysSinceMmdlSubmission:
    handler: handlers/daysSinceMmdlSubmission.handler
    environment:
      region: ${self:provider.region}
      project: ${self:custom.project}
      stage: ${sls:stage}
      mmdlTableName: ${param:mmdlTableName}

stepFunctions:
  stateMachines:
    compareAlertFunc:
      name: ${self:service}-${sls:stage}-alerting
      id: MMDLAlertingStateMachine
      definition:
        Comment: "A State Machine to orchestrate a CMS alerting workflow for MMDL."
        StartAt: InitialWait
        States:
          InitialWait:
            Type: Wait
            Seconds: ${param:initialWaitSec}
            Next: DoesSeatoolRecordExistTask
          DoesSeatoolRecordExistTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-seatoolRecordExist"
            Parameters:
              Payload.$: $
              Context.$: $$
            Next: HandleSeatoolRecordExistChoice
          HandleSeatoolRecordExistChoice:
            Type: Choice
            Choices:
              - Variable: $.seatoolExist
                BooleanEquals: true
                Next: CompareTask
              - Variable: $.seatoolExist
                BooleanEquals: false
                Next: DaysSinceMmdlSubmissionTask
            Default: DaysSinceMmdlSubmissionTask # maybe default tasks could be an error handler since choice should match
          DaysSinceMmdlSubmissionTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-daysSinceMmdlSubmission"
            Parameters:
              Payload.$: $
              Context.$: $$
            Next: SignedSinceChoice
          SignedSinceChoice:
            Type: Choice
            Choices:
              - And:
                  - Variable: $.daysSinceMmdlSigned
                    NumericGreaterThanEquals: ${param:signedSinceChoiceDays}
                  - Variable: $.mmdlSigned
                    BooleanEquals: true
                Next: SendRecordDoesNotExistTask
            Default: RecordAgeChoice
          SendRecordDoesNotExistTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-sendAlert"
            Parameters:
              Payload.$: $
              Context.$: $$
            Next: RecordAgeChoice
          RecordAgeChoice:
            Type: Choice
            Choices:
              - Variable: $.daysSinceMmdlSigned
                NumericGreaterThanEquals: ${param:recordAgeChoiceDays}
                Next: SuccessState
            Default: FailState
          CompareTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-compare"
            Parameters:
              Payload.$: $
              Context.$: $$
            Next: RecordsMatchChoice
          RecordsMatchChoice:
            Type: Choice
            Choices:
              - Variable: $.match
                BooleanEquals: true
                Next: SuccessState
              - Variable: $.match
                BooleanEquals: false
                Next: SendAlertTask
            Default: SendAlertTask
          SendAlertTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-sendAlert"
            Parameters:
              Payload.$: $
              Context.$: $$
            Next: SuccessState
          SuccessState:
            Type: Succeed
          FailState:
            Type: Fail
